---
- name: Sync Ansible Vault secrets to AWS Secrets Manager
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - aws_secrets
  tasks:

    - name: Check Ansible collections
      ansible.builtin.include_tasks:
        file: ../tasks/collections.yml

    - name: Check AWS CLI
      ansible.builtin.include_tasks:
        file: ../tasks/aws_cli.yml

    - name: Run Terraform
      ansible.builtin.include_tasks:
        file: ../tasks/terraform.yml