---
- name: Create/update AWS Secrets Manager secret
  amazon.aws.secretsmanager_secret:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    state: present
    region: "{{ aws_region }}"
  loop: "{{ aws_secrets }}"
  loop_control:
    label: "{{ item.name }}"
